services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/quiz-proctor --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/quiz-proctor
      JWT_SECRET: supersecretjwt
      CLIENT_ORIGIN: http://localhost:5173,http://localhost:5174,http://localhost:3000
      NODE_ENV: development
      CORS_ALLOW_ALL: 'false'
      CORS_DOMAIN: https://smart-quiz-platform.pentacoresolutions.in
    ports:
      - '4000:4000'
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
      - VITE_WS_URL=ws://localhost:4000
    ports:
      - '3000:80'
      - '80:80'
    depends_on:
      - backend
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    command: ["http", "--url=smart-quiz-platform.pentacoresolutions.in", "http://frontend:80"]
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN:-2up1MIsXh1y3lw23d3miduvT1N6_3TJFWnuVStwJT7xBqfUN6}
    ports:
      - '4040:4040'
    depends_on:
      - frontend
    restart: unless-stopped

volumes:
  mongo-data:
