#!/usr/bin/env python3
"""
Generate comprehensive topic-based question bank for programming languages
Creates diverse questions across multiple important topics
"""

import json
import random

# Define comprehensive question templates for each language
QUESTION_TEMPLATES = {
    "javascript": {
        "Variables and Data Types": [
            {"q": "What keyword is used to declare a block-scoped variable?", "type": "mc", "opts": ["let", "var", "const", "variable"], "ans": 0},
            {"q": "Which data type is used for decimal numbers in JavaScript?", "type": "mc", "opts": ["float", "decimal", "number", "double"], "ans": 2},
            {"q": "JavaScript has dynamic typing.", "type": "tf", "ans": True},
            {"q": "The __ keyword declares a constant that cannot be reassigned.", "type": "fb", "ans": ["const"]},
            {"q": "What is the output of typeof undefined?", "type": "mc", "opts": ["undefined", "null", "object", "string"], "ans": 0},
            {"q": "Variables declared with var are function-scoped.", "type": "tf", "ans": True},
            {"q": "The __ operator checks both value and type equality.", "type": "fb", "ans": ["===", "strict equality"]},
            {"q": "JavaScript supports BigInt for arbitrary-precision integers.", "type": "tf", "ans": True},
            {"q": "What is the result of typeof null?", "type": "mc", "opts": ["object", "null", "undefined", "number"], "ans": 0},
            {"q": "NaN (Not-a-Number) is of type number.", "type": "tf", "ans": True},
            {"q": "The __ keyword was introduced in ES6 for block-scoped declarations.", "type": "fb", "ans": ["let"]},
            {"q": "Which symbol represents template literals?", "type": "mc", "opts": ["Backticks ``", "Single quotes ''", "Double quotes \"\"", "Brackets []"], "ans": 0},
            {"q": "JavaScript variables are case-sensitive.", "type": "tf", "ans": True},
            {"q": "The __ value represents intentional absence of any value.", "type": "fb", "ans": ["null"]},
            {"q": "What is the maximum safe integer in JavaScript?", "type": "mc", "opts": ["2^53 - 1", "2^31 - 1", "2^63 - 1", "Infinity"], "ans": 0},
            {"q": "Symbols are always unique and immutable.", "type": "tf", "ans": True},
        ],
        "Functions": [
            {"q": "Which keyword is used to define a function?", "type": "mc", "opts": ["function", "func", "def", "method"], "ans": 0},
            {"q": "Arrow functions have their own 'this' binding.", "type": "tf", "ans": False},
            {"q": "The __ keyword returns a value from a function.", "type": "fb", "ans": ["return"]},
            {"q": "What syntax defines an arrow function?", "type": "mc", "opts": ["() => {}", "() -> {}", "function() {}", "lambda() {}"], "ans": 0},
            {"q": "Functions in JavaScript are first-class objects.", "type": "tf", "ans": True},
            {"q": "Which method calls a function with a given this value?", "type": "mc", "opts": ["call()", "invoke()", "execute()", "run()"], "ans": 0},
            {"q": "IIFE stands for Immediately Invoked Function Expression.", "type": "tf", "ans": True},
            {"q": "What method binds a function permanently to a context?", "type": "mc", "opts": ["bind()", "attach()", "link()", "connect()"], "ans": 0},
            {"q": "Default parameters were introduced in ES6.", "type": "tf", "ans": True},
            {"q": "The __ parameter collects remaining arguments into an array.", "type": "fb", "ans": ["rest", "..."]},
            {"q": "Which allows functions to be passed as arguments?", "type": "mc", "opts": ["Higher-order functions", "Callback functions", "Lambda functions", "Anonymous functions"], "ans": 0},
            {"q": "Closures have access to outer function variables.", "type": "tf", "ans": True},
            {"q": "The __ method applies a function with an array of arguments.", "type": "fb", "ans": ["apply", "apply()"]},
            {"q": "What is a function that returns another function called?", "type": "mc", "opts": ["Curried function", "Nested function", "Recursive function", "Callback function"], "ans": 0},
            {"q": "Generator functions use the function* syntax.", "type": "tf", "ans": True},
            {"q": "The __ keyword yields values in generator functions.", "type": "fb", "ans": ["yield"]},
        ],
        "Arrays and Iteration": [
            {"q": "Which method adds elements to the end of an array?", "type": "mc", "opts": ["push()", "append()", "add()", "insert()"], "ans": 0},
            {"q": "Arrays in JavaScript can hold mixed data types.", "type": "tf", "ans": True},
            {"q": "The __ method removes the last element from an array.", "type": "fb", "ans": ["pop", "pop()"]},
            {"q": "What method creates a new array with filtered elements?", "type": "mc", "opts": ["filter()", "select()", "where()", "find()"], "ans": 0},
            {"q": "Array.isArray() checks if a value is an array.", "type": "tf", "ans": True},
            {"q": "The __ method joins array elements into a string.", "type": "fb", "ans": ["join", "join()"]},
            {"q": "Which method adds elements to the beginning of an array?", "type": "mc", "opts": ["unshift()", "prepend()", "addFirst()", "push()"], "ans": 0},
            {"q": "The spread operator for arrays is written as ...", "type": "tf", "ans": True},
            {"q": "What method transforms each array element?", "type": "mc", "opts": ["map()", "transform()", "convert()", "change()"], "ans": 0},
            {"q": "The reduce() method accumulates array values into a single result.", "type": "tf", "ans": True},
            {"q": "The __ method returns the first element matching a condition.", "type": "fb", "ans": ["find", "find()"]},
            {"q": "Which method removes elements from an array?", "type": "mc", "opts": ["splice()", "slice()", "cut()", "remove()"], "ans": 0},
            {"q": "forEach() returns a new array.", "type": "tf", "ans": False},
            {"q": "The __ method tests if all elements pass a condition.", "type": "fb", "ans": ["every", "every()"]},
            {"q": "What method checks if at least one element passes a test?", "type": "mc", "opts": ["some()", "any()", "exists()", "contains()"], "ans": 0},
            {"q": "Array destructuring allows extracting multiple values at once.", "type": "tf", "ans": True},
        ],
        "Objects and Prototypes": [
            {"q": "How do you access an object property using bracket notation?", "type": "mc", "opts": ["obj['key']", "obj.key", "obj->key", "obj::key"], "ans": 0},
            {"q": "Objects in JavaScript are passed by reference.", "type": "tf", "ans": True},
            {"q": "The __ method returns an array of object keys.", "type": "fb", "ans": ["Object.keys", "keys"]},
            {"q": "What method creates a new object from an existing one?", "type": "mc", "opts": ["Object.create()", "new Object()", "Object.make()", "Object.copy()"], "ans": 0},
            {"q": "Object property names can be symbols or strings.", "type": "tf", "ans": True},
            {"q": "The __ operator deletes a property from an object.", "type": "fb", "ans": ["delete"]},
            {"q": "Which method merges multiple objects?", "type": "mc", "opts": ["Object.assign()", "Object.merge()", "Object.combine()", "Object.join()"], "ans": 0},
            {"q": "Object destructuring allows extracting multiple properties at once.", "type": "tf", "ans": True},
            {"q": "What method returns an array of object values?", "type": "mc", "opts": ["Object.values()", "Object.getValues()", "values()", "getValues()"], "ans": 0},
            {"q": "The prototype chain is used for inheritance in JavaScript.", "type": "tf", "ans": True},
            {"q": "The __ method defines a new property on an object.", "type": "fb", "ans": ["Object.defineProperty"]},
            {"q": "Which method prevents modifications to an object?", "type": "mc", "opts": ["Object.freeze()", "Object.lock()", "Object.seal()", "Object.protect()"], "ans": 0},
            {"q": "hasOwnProperty() checks if a property exists directly on an object.", "type": "tf", "ans": True},
            {"q": "The __ property references an object's prototype.", "type": "fb", "ans": ["__proto__", "prototype"]},
            {"q": "What method returns key-value pairs as arrays?", "type": "mc", "opts": ["Object.entries()", "Object.pairs()", "Object.items()", "Object.tuples()"], "ans": 0},
            {"q": "Object.seal() prevents adding or removing properties but allows modification.", "type": "tf", "ans": True},
        ],
        "Promises and Async": [
            {"q": "A Promise can be in which states?", "type": "mc", "opts": ["pending, fulfilled, rejected", "waiting, done, failed", "open, closed, error", "running, complete, broken"], "ans": 0},
            {"q": "The async keyword makes a function return a Promise.", "type": "tf", "ans": True},
            {"q": "The __ keyword pauses async function execution.", "type": "fb", "ans": ["await"]},
            {"q": "Which method runs multiple promises concurrently?", "type": "mc", "opts": ["Promise.all()", "Promise.race()", "Promise.run()", "Promise.execute()"], "ans": 0},
            {"q": "await can only be used inside async functions.", "type": "tf", "ans": True},
            {"q": "The __ method handles promise rejection.", "type": "fb", "ans": ["catch", "catch()"]},
            {"q": "What executes after a promise settles (fulfilled or rejected)?", "type": "mc", "opts": ["finally()", "complete()", "done()", "settle()"], "ans": 0},
            {"q": "Promise.race() returns when the first promise settles.", "type": "tf", "ans": True},
            {"q": "Which method returns a promise that resolves immediately?", "type": "mc", "opts": ["Promise.resolve()", "Promise.create()", "Promise.make()", "Promise.instant()"], "ans": 0},
            {"q": "Promise.allSettled() waits for all promises regardless of outcome.", "type": "tf", "ans": True},
            {"q": "The __ method chains promise handlers.", "type": "fb", "ans": ["then", "then()"]},
            {"q": "What returns a rejected promise?", "type": "mc", "opts": ["Promise.reject()", "Promise.fail()", "Promise.error()", "Promise.throw()"], "ans": 0},
            {"q": "Promises help avoid callback hell.", "type": "tf", "ans": True},
            {"q": "The __ executes when promise resolves successfully.", "type": "fb", "ans": ["then", "resolve handler"]},
            {"q": "Which returns the first fulfilled or all rejected?", "type": "mc", "opts": ["Promise.any()", "Promise.some()", "Promise.first()", "Promise.one()"], "ans": 0},
            {"q": "Async functions automatically wrap return values in promises.", "type": "tf", "ans": True},
        ],
        "DOM Manipulation": [
            {"q": "Which method selects an element by ID?", "type": "mc", "opts": ["getElementById()", "selectById()", "findId()", "getElement()"], "ans": 0},
            {"q": "querySelector() returns the first matching element.", "type": "tf", "ans": True},
            {"q": "The __ method selects all matching elements.", "type": "fb", "ans": ["querySelectorAll"]},
            {"q": "What property changes an element's HTML content?", "type": "mc", "opts": ["innerHTML", "content", "html", "innerContent"], "ans": 0},
            {"q": "textContent is safer than innerHTML for user input.", "type": "tf", "ans": True},
            {"q": "The __ method adds a CSS class to an element.", "type": "fb", "ans": ["classList.add", "add"]},
            {"q": "Which method creates a new DOM element?", "type": "mc", "opts": ["createElement()", "create()", "newElement()", "makeElement()"], "ans": 0},
            {"q": "appendChild() adds a node to the end of a parent's children.", "type": "tf", "ans": True},
            {"q": "The __ method removes a child element.", "type": "fb", "ans": ["removeChild", "remove"]},
            {"q": "What event fires when DOM is fully loaded?", "type": "mc", "opts": ["DOMContentLoaded", "load", "ready", "onload"], "ans": 0},
            {"q": "addEventListener() can attach multiple handlers to one event.", "type": "tf", "ans": True},
            {"q": "The __ property accesses element attributes.", "type": "fb", "ans": ["getAttribute", "attributes"]},
            {"q": "Which method clones a DOM node?", "type": "mc", "opts": ["cloneNode()", "copy()", "duplicate()", "clone()"], "ans": 0},
            {"q": "Event bubbling propagates from child to parent elements.", "type": "tf", "ans": True},
            {"q": "The __ method prevents default browser behavior.", "type": "fb", "ans": ["preventDefault"]},
            {"q": "What property provides the element that triggered an event?", "type": "mc", "opts": ["event.target", "event.source", "event.element", "event.sender"], "ans": 0},
        ],
        "ES6+ Features": [
            {"q": "Which feature allows exporting multiple named values?", "type": "mc", "opts": ["Named exports", "Default export", "Module export", "Batch export"], "ans": 0},
            {"q": "Template literals support multi-line strings.", "type": "tf", "ans": True},
            {"q": "The __ operator provides default values for null/undefined.", "type": "fb", "ans": ["??", "nullish coalescing"]},
            {"q": "What feature enables import/export between modules?", "type": "mc", "opts": ["ES6 Modules", "CommonJS", "RequireJS", "AMD"], "ans": 0},
            {"q": "Destructuring can extract nested object properties.", "type": "tf", "ans": True},
            {"q": "The __ chaining operator safely accesses nested properties.", "type": "fb", "ans": ["?.", "optional chaining"]},
            {"q": "Which creates a new class in ES6?", "type": "mc", "opts": ["class keyword", "function constructor", "Object.create()", "prototype"], "ans": 0},
            {"q": "Arrow functions inherit this from enclosing scope.", "type": "tf", "ans": True},
            {"q": "The __ method creates a shallow copy of an array.", "type": "fb", "ans": ["slice", "..."]},
            {"q": "What provides unique identifiers as property keys?", "type": "mc", "opts": ["Symbol", "UUID", "GUID", "Hash"], "ans": 0},
            {"q": "for...of loop iterates over iterable objects.", "type": "tf", "ans": True},
            {"q": "The __ statement imports all exports from a module.", "type": "fb", "ans": ["import *", "*"]},
            {"q": "Which method finds an object's prototype?", "type": "mc", "opts": ["Object.getPrototypeOf()", "getProto()", "prototype()", "protoOf()"], "ans": 0},
            {"q": "WeakSet allows automatic garbage collection of objects.", "type": "tf", "ans": True},
            {"q": "The __ exports a single default value from a module.", "type": "fb", "ans": ["export default"]},
            {"q": "What creates an iterator from an iterable?", "type": "mc", "opts": ["Symbol.iterator", "iterator()", "getIterator()", "iter()"], "ans": 0},
        ],
    },
    "python": {
        "Variables and Data Types": [
            {"q": "What is the correct way to assign a value to a variable?", "type": "mc", "opts": ["x = 5", "var x = 5", "let x = 5", "int x = 5"], "ans": 0},
            {"q": "Python is dynamically typed.", "type": "tf", "ans": True},
            {"q": "The __ function returns the type of a variable.", "type": "fb", "ans": ["type", "type()"]},
            {"q": "Which of these is NOT a Python data type?", "type": "mc", "opts": ["char", "int", "float", "str"], "ans": 0},
            {"q": "Variables in Python can start with a number.", "type": "tf", "ans": False},
            {"q": "The __ keyword defines a None value.", "type": "fb", "ans": ["None"]},
            {"q": "What is the result of 10 / 3 in Python 3?", "type": "mc", "opts": ["3.333...", "3", "3.0", "Error"], "ans": 0},
            {"q": "Python supports complex numbers natively.", "type": "tf", "ans": True},
            {"q": "The __ function converts a value to an integer.", "type": "fb", "ans": ["int", "int()"]},
            {"q": "Which operator performs floor division?", "type": "mc", "opts": ["//", "/", "%", "div"], "ans": 0},
            {"q": "Strings in Python are immutable.", "type": "tf", "ans": True},
            {"q": "The __ function returns the length of an object.", "type": "fb", "ans": ["len", "len()"]},
            {"q": "What represents infinity in Python?", "type": "mc", "opts": ["float('inf')", "Infinity", "INF", "Math.inf"], "ans": 0},
            {"q": "Multiple variables can be assigned in one line.", "type": "tf", "ans": True},
            {"q": "The __ checks if a variable is defined.", "type": "fb", "ans": ["in", "hasattr"]},
            {"q": "Which function checks if a value is an integer?", "type": "mc", "opts": ["isinstance(x, int)", "isint(x)", "type(x) == int", "checkint(x)"], "ans": 0},
        ],
        "Lists and Tuples": [
            {"q": "Which method adds an item to the end of a list?", "type": "mc", "opts": ["append()", "add()", "push()", "insert()"], "ans": 0},
            {"q": "Tuples are immutable in Python.", "type": "tf", "ans": True},
            {"q": "The __ method removes an item from a list by value.", "type": "fb", "ans": ["remove", "remove()"]},
            {"q": "What operator creates a list slice?", "type": "mc", "opts": [":", "..", "->", "::"], "ans": 0},
            {"q": "Lists can contain mixed data types.", "type": "tf", "ans": True},
            {"q": "The __ function returns the length of a list.", "type": "fb", "ans": ["len", "len()"]},
            {"q": "Which method sorts a list in place?", "type": "mc", "opts": ["sort()", "sorted()", "order()", "arrange()"], "ans": 0},
            {"q": "List comprehensions provide a concise way to create lists.", "type": "tf", "ans": True},
            {"q": "The __ method inserts an item at a specific index.", "type": "fb", "ans": ["insert", "insert()"]},
            {"q": "What method returns and removes an item at an index?", "type": "mc", "opts": ["pop()", "remove()", "delete()", "extract()"], "ans": 0},
            {"q": "Negative indices access elements from the end of a list.", "type": "tf", "ans": True},
            {"q": "The __ method extends a list with another iterable.", "type": "fb", "ans": ["extend", "extend()"]},
            {"q": "Which function creates a new sorted list?", "type": "mc", "opts": ["sorted()", "sort()", "order()", "arrange()"], "ans": 0},
            {"q": "Lists are mutable sequences in Python.", "type": "tf", "ans": True},
            {"q": "The __ operator replicates a list n times.", "type": "fb", "ans": ["*", "multiply"]},
            {"q": "What method counts occurrences of a value in a list?", "type": "mc", "opts": ["count()", "frequency()", "occurrences()", "find()"], "ans": 0},
        ],
        "Dictionaries and Sets": [
            {"q": "How do you create an empty dictionary?", "type": "mc", "opts": ["{}", "[]", "dict()", "Both {} and dict()"], "ans": 3},
            {"q": "Dictionary keys must be immutable.", "type": "tf", "ans": True},
            {"q": "The __ method returns all keys in a dictionary.", "type": "fb", "ans": ["keys", "keys()"]},
            {"q": "Which method safely gets a value with a default?", "type": "mc", "opts": ["get()", "fetch()", "retrieve()", "find()"], "ans": 0},
            {"q": "Dictionaries maintain insertion order in Python 3.7+.", "type": "tf", "ans": True},
            {"q": "The __ method removes a key-value pair from a dictionary.", "type": "fb", "ans": ["pop", "pop()", "del"]},
            {"q": "What returns both keys and values as tuples?", "type": "mc", "opts": ["items()", "pairs()", "entries()", "tuples()"], "ans": 0},
            {"q": "Dictionary comprehensions create dictionaries concisely.", "type": "tf", "ans": True},
            {"q": "The __ method updates a dictionary with another.", "type": "fb", "ans": ["update", "update()"]},
            {"q": "Which creates a set in Python?", "type": "mc", "opts": ["{1, 2, 3}", "[1, 2, 3]", "(1, 2, 3)", "set[1, 2, 3]"], "ans": 0},
            {"q": "Sets automatically remove duplicate values.", "type": "tf", "ans": True},
            {"q": "The __ method adds an element to a set.", "type": "fb", "ans": ["add", "add()"]},
            {"q": "What operation finds common elements between sets?", "type": "mc", "opts": ["intersection", "union", "difference", "common"], "ans": 0},
            {"q": "Frozenset is an immutable version of set.", "type": "tf", "ans": True},
            {"q": "The __ method merges sets returning a new set.", "type": "fb", "ans": ["union", "union()"]},
            {"q": "Which finds elements in one set but not another?", "type": "mc", "opts": ["difference()", "subtract()", "exclude()", "minus()"], "ans": 0},
        ],
        "Functions and Decorators": [
            {"q": "Which keyword defines a function in Python?", "type": "mc", "opts": ["def", "function", "func", "define"], "ans": 0},
            {"q": "Python functions can return multiple values.", "type": "tf", "ans": True},
            {"q": "The __ keyword creates an anonymous function.", "type": "fb", "ans": ["lambda"]},
            {"q": "What is the default return value of a function?", "type": "mc", "opts": ["None", "0", "null", "undefined"], "ans": 0},
            {"q": "*args allows a function to accept variable arguments.", "type": "tf", "ans": True},
            {"q": "The __ keyword returns a value from a function.", "type": "fb", "ans": ["return"]},
            {"q": "Which decorator makes a method static?", "type": "mc", "opts": ["@staticmethod", "@static", "@classmethod", "@method"], "ans": 0},
            {"q": "Functions in Python are first-class objects.", "type": "tf", "ans": True},
            {"q": "The __ parameter accepts keyword arguments as a dictionary.", "type": "fb", "ans": ["**kwargs", "kwargs"]},
            {"q": "What decorator makes a method a class method?", "type": "mc", "opts": ["@classmethod", "@class", "@static", "@method"], "ans": 0},
            {"q": "Decorators modify function behavior without changing source code.", "type": "tf", "ans": True},
            {"q": "The __ keyword makes a variable global.", "type": "fb", "ans": ["global"]},
            {"q": "Which allows default parameter values?", "type": "mc", "opts": ["def func(x=10)", "def func(x:10)", "def func(x->10)", "def func(x|10)"], "ans": 0},
            {"q": "Nested functions have access to enclosing function variables.", "type": "tf", "ans": True},
            {"q": "The __ keyword allows modifying nonlocal variables.", "type": "fb", "ans": ["nonlocal"]},
            {"q": "What decorator caches function results?", "type": "mc", "opts": ["@lru_cache", "@cache", "@memoize", "@remember"], "ans": 0},
        ],
        "Classes and OOP": [
            {"q": "Which keyword creates a class in Python?", "type": "mc", "opts": ["class", "Class", "object", "struct"], "ans": 0},
            {"q": "Python supports multiple inheritance.", "type": "tf", "ans": True},
            {"q": "The __ method initializes a new object.", "type": "fb", "ans": ["__init__", "init"]},
            {"q": "What is the first parameter of instance methods?", "type": "mc", "opts": ["self", "this", "me", "obj"], "ans": 0},
            {"q": "Private attributes are denoted by a double underscore prefix.", "type": "tf", "ans": True},
            {"q": "The __ method is called when an object is deleted.", "type": "fb", "ans": ["__del__", "del"]},
            {"q": "Which decorator creates a class method?", "type": "mc", "opts": ["@classmethod", "@class", "@static", "@method"], "ans": 0},
            {"q": "Python uses duck typing for polymorphism.", "type": "tf", "ans": True},
            {"q": "The __ method returns a string representation of an object.", "type": "fb", "ans": ["__str__", "str"]},
            {"q": "What method defines object representation for debugging?", "type": "mc", "opts": ["__repr__", "__str__", "__debug__", "__show__"], "ans": 0},
            {"q": "Property decorator creates managed attributes.", "type": "tf", "ans": True},
            {"q": "The __ method compares two objects for equality.", "type": "fb", "ans": ["__eq__", "eq"]},
            {"q": "Which allows operator overloading for addition?", "type": "mc", "opts": ["__add__", "__plus__", "__sum__", "__combine__"], "ans": 0},
            {"q": "Abstract base classes require subclasses to implement methods.", "type": "tf", "ans": True},
            {"q": "The __ module provides abstract base classes.", "type": "fb", "ans": ["abc"]},
            {"q": "What makes an object iterable?", "type": "mc", "opts": ["__iter__ method", "__next__ method", "__loop__ method", "__iterate__ method"], "ans": 0},
        ],
        "File Handling and I/O": [
            {"q": "Which function opens a file in Python?", "type": "mc", "opts": ["open()", "file()", "read()", "load()"], "ans": 0},
            {"q": "The with statement ensures files are properly closed.", "type": "tf", "ans": True},
            {"q": "The __ mode opens a file for reading.", "type": "fb", "ans": ["r", "'r'"]},
            {"q": "What mode appends to a file without truncating?", "type": "mc", "opts": ["'a'", "'w'", "'r+'", "'x'"], "ans": 0},
            {"q": "Binary mode is specified with 'b' suffix.", "type": "tf", "ans": True},
            {"q": "The __ method reads the entire file content.", "type": "fb", "ans": ["read", "read()"]},
            {"q": "Which method reads a file line by line?", "type": "mc", "opts": ["readline()", "readlines()", "read()", "getline()"], "ans": 0},
            {"q": "Files opened with 'w' mode truncate existing content.", "type": "tf", "ans": True},
            {"q": "The __ method writes a string to a file.", "type": "fb", "ans": ["write", "write()"]},
            {"q": "What returns all lines as a list?", "type": "mc", "opts": ["readlines()", "readline()", "getlines()", "lines()"], "ans": 0},
            {"q": "The tell() method returns current file position.", "type": "tf", "ans": True},
            {"q": "The __ method moves file pointer to a position.", "type": "fb", "ans": ["seek", "seek()"]},
            {"q": "Which module handles file paths across OS?", "type": "mc", "opts": ["os.path", "pathlib", "Both os.path and pathlib", "filepath"], "ans": 2},
            {"q": "Context managers use __enter__ and __exit__ methods.", "type": "tf", "ans": True},
            {"q": "The __ function removes a file.", "type": "fb", "ans": ["os.remove", "remove"]},
            {"q": "What checks if a file exists?", "type": "mc", "opts": ["os.path.exists()", "file.exists()", "exists()", "isfile()"], "ans": 0},
        ],
        "Exception Handling": [
            {"q": "Which keyword catches exceptions in Python?", "type": "mc", "opts": ["except", "catch", "error", "handle"], "ans": 0},
            {"q": "The try block must be followed by except or finally.", "type": "tf", "ans": True},
            {"q": "The __ keyword raises an exception.", "type": "fb", "ans": ["raise"]},
            {"q": "What block always executes after try-except?", "type": "mc", "opts": ["finally", "always", "ensure", "cleanup"], "ans": 0},
            {"q": "Multiple except blocks can handle different exceptions.", "type": "tf", "ans": True},
            {"q": "The __ keyword provides an alternate if no exception occurs.", "type": "fb", "ans": ["else"]},
            {"q": "Which is the base class for all exceptions?", "type": "mc", "opts": ["BaseException", "Exception", "Error", "StandardError"], "ans": 0},
            {"q": "Custom exceptions should inherit from Exception class.", "type": "tf", "ans": True},
            {"q": "The __ exception is raised for division by zero.", "type": "fb", "ans": ["ZeroDivisionError"]},
            {"q": "What exception occurs when accessing invalid indices?", "type": "mc", "opts": ["IndexError", "KeyError", "ValueError", "TypeError"], "ans": 0},
            {"q": "KeyError is raised when a dictionary key doesn't exist.", "type": "tf", "ans": True},
            {"q": "The __ exception handles type mismatches.", "type": "fb", "ans": ["TypeError"]},
            {"q": "Which exception is raised for invalid values?", "type": "mc", "opts": ["ValueError", "TypeError", "KeyError", "AttributeError"], "ans": 0},
            {"q": "Assertions raise AssertionError when false.", "type": "tf", "ans": True},
            {"q": "The __ statement tests conditions and raises errors.", "type": "fb", "ans": ["assert"]},
            {"q": "What handles missing attributes on objects?", "type": "mc", "opts": ["AttributeError", "KeyError", "NameError", "TypeError"], "ans": 0},
        ],
    },
    "java": {
        "Variables and Data Types": [
            {"q": "What is the default value of an uninitialized int variable in Java?", "type": "mc", "opts": ["0", "null", "undefined", "Compiler error"], "ans": 0},
            {"q": "Which wrapper class is used for primitive type 'int'?", "type": "mc", "opts": ["Int", "Integer", "Number", "IntWrapper"], "ans": 1},
            {"q": "What is autoboxing in Java?", "type": "mc", "opts": ["Automatic conversion of primitive to wrapper", "Boxing classes automatically", "Auto-generating getter/setter", "Automatic memory allocation"], "ans": 0},
            {"q": "Can you reassign a 'final' variable in Java?", "type": "tf", "ans": False},
            {"q": "What is the size of 'long' data type in Java?", "type": "fb", "ans": ["8 bytes", "8"]},
            {"q": "Which keyword is used to define a constant in Java?", "type": "mc", "opts": ["const", "constant", "final", "static"], "ans": 2},
            {"q": "What happens when you assign an int to a byte without casting?", "type": "mc", "opts": ["Automatic conversion", "Compilation error", "Runtime error", "Value truncation"], "ans": 1},
            {"q": "Is 'String' a primitive data type in Java?", "type": "tf", "ans": False},
            {"q": "What is the range of 'byte' data type?", "type": "mc", "opts": ["-128 to 127", "0 to 255", "-256 to 255", "-32768 to 32767"], "ans": 0},
            {"q": "Which data type should be used for decimal values with precision?", "type": "mc", "opts": ["float", "double", "BigDecimal", "Decimal"], "ans": 2},
            {"q": "Can a variable be both 'static' and 'final'?", "type": "tf", "ans": True},
            {"q": "What is the default value of a boolean variable?", "type": "fb", "ans": ["false"]},
            {"q": "Which keyword prevents a variable from being serialized?", "type": "mc", "opts": ["volatile", "transient", "synchronized", "native"], "ans": 1},
            {"q": "What is the difference between '==' and '.equals()' for String comparison?", "type": "mc", "opts": ["No difference", "== compares references, equals() compares content", "== is faster", "equals() compares references"], "ans": 1},
            {"q": "Can primitive types be used in generics?", "type": "tf", "ans": False},
            {"q": "What is the keyword to define a variable that can be modified by multiple threads?", "type": "fb", "ans": ["volatile"]},
        ],
        "Classes and Objects": [
            {"q": "What is encapsulation in Java?", "type": "mc", "opts": ["Hiding implementation details", "Inheriting properties", "Multiple forms", "Abstract behavior"], "ans": 0},
            {"q": "Which access modifier provides the most restricted access?", "type": "mc", "opts": ["public", "protected", "default", "private"], "ans": 3},
            {"q": "What is a constructor in Java?", "type": "mc", "opts": ["A method to destroy objects", "A special method to initialize objects", "A static method", "A final method"], "ans": 1},
            {"q": "Can a constructor be private in Java?", "type": "tf", "ans": True},
            {"q": "What is the default constructor?", "type": "fb", "ans": ["no parameters", "parameterless"]},
            {"q": "Which keyword is used to refer to the current object?", "type": "mc", "opts": ["self", "this", "current", "object"], "ans": 1},
            {"q": "Can a class have multiple constructors?", "type": "tf", "ans": True},
            {"q": "What is method overloading?", "type": "mc", "opts": ["Same method name, different parameters", "Different method names", "Overriding parent methods", "Loading multiple methods"], "ans": 0},
            {"q": "What happens if you don't define a constructor?", "type": "mc", "opts": ["Compilation error", "Java provides default constructor", "Runtime error", "Object cannot be created"], "ans": 1},
            {"q": "Can static methods access instance variables directly?", "type": "tf", "ans": False},
            {"q": "What is a singleton pattern?", "type": "mc", "opts": ["One instance per thread", "Only one instance of a class", "One method per class", "Single inheritance"], "ans": 1},
            {"q": "What keyword is used to prevent method overriding?", "type": "fb", "ans": ["final"]},
            {"q": "What is the purpose of the 'super' keyword?", "type": "mc", "opts": ["Call superclass constructor/methods", "Create superior objects", "Override methods", "Access static members"], "ans": 0},
            {"q": "Can an inner class access private members of outer class?", "type": "tf", "ans": True},
            {"q": "What is an anonymous inner class?", "type": "mc", "opts": ["A class without a name", "A private class", "A static class", "An abstract class"], "ans": 0},
            {"q": "How many objects are created: 'String s1 = new String(\"test\"); String s2 = \"test\";'?", "type": "fb", "ans": ["2"]},
        ],
        "Inheritance and Polymorphism": [
            {"q": "Which keyword is used to inherit a class in Java?", "type": "mc", "opts": ["implements", "extends", "inherits", "derives"], "ans": 1},
            {"q": "Does Java support multiple inheritance?", "type": "tf", "ans": False},
            {"q": "What is method overriding?", "type": "mc", "opts": ["Redefining parent method in child class", "Overloading methods", "Hiding methods", "Static dispatch"], "ans": 0},
            {"q": "Which annotation indicates method overriding?", "type": "fb", "ans": ["@Override", "Override"]},
            {"q": "Can you override a static method in Java?", "type": "tf", "ans": False},
            {"q": "What is polymorphism?", "type": "mc", "opts": ["Many forms of a single entity", "Multiple classes", "Many objects", "Multiple threads"], "ans": 0},
            {"q": "What is compile-time polymorphism?", "type": "mc", "opts": ["Method overloading", "Method overriding", "Inheritance", "Abstraction"], "ans": 0},
            {"q": "What is runtime polymorphism?", "type": "mc", "opts": ["Method overloading", "Method overriding", "Static binding", "Early binding"], "ans": 1},
            {"q": "Can a final class be inherited?", "type": "tf", "ans": False},
            {"q": "What is the superclass of all classes in Java?", "type": "fb", "ans": ["Object"]},
            {"q": "Can you override a private method?", "type": "tf", "ans": False},
            {"q": "What is an abstract class?", "type": "mc", "opts": ["A class that cannot be instantiated", "A final class", "A static class", "A private class"], "ans": 0},
            {"q": "Can an abstract class have concrete methods?", "type": "tf", "ans": True},
            {"q": "What keyword is used to define an abstract method?", "type": "fb", "ans": ["abstract"]},
            {"q": "What is covariant return type?", "type": "mc", "opts": ["Overriding method can return subtype", "Return multiple types", "Return void", "Return same type only"], "ans": 0},
            {"q": "Can constructors be inherited in Java?", "type": "tf", "ans": False},
        ],
        "Collections Framework": [
            {"q": "Which interface is the root of the Collections hierarchy?", "type": "mc", "opts": ["List", "Set", "Collection", "Map"], "ans": 2},
            {"q": "Does ArrayList maintain insertion order?", "type": "tf", "ans": True},
            {"q": "What is the difference between ArrayList and LinkedList?", "type": "mc", "opts": ["ArrayList uses array, LinkedList uses doubly linked list", "No difference", "ArrayList is slower", "LinkedList cannot grow"], "ans": 0},
            {"q": "Which collection does not allow duplicate elements?", "type": "mc", "opts": ["List", "Set", "Queue", "Deque"], "ans": 1},
            {"q": "What is the time complexity for ArrayList get operation?", "type": "fb", "ans": ["O(1)", "1", "constant"]},
            {"q": "Is HashMap synchronized?", "type": "tf", "ans": False},
            {"q": "What is the difference between HashMap and TreeMap?", "type": "mc", "opts": ["HashMap is unordered, TreeMap is sorted", "No difference", "TreeMap is faster", "HashMap uses trees"], "ans": 0},
            {"q": "Which collection is thread-safe?", "type": "mc", "opts": ["ArrayList", "HashMap", "Vector", "LinkedList"], "ans": 2},
            {"q": "Can a HashMap have null keys?", "type": "tf", "ans": True},
            {"q": "What is the default capacity of ArrayList?", "type": "fb", "ans": ["10"]},
            {"q": "What is a Queue in Java Collections?", "type": "mc", "opts": ["FIFO data structure", "LIFO data structure", "Random access", "Sorted structure"], "ans": 0},
            {"q": "Does HashSet allow null values?", "type": "tf", "ans": True},
            {"q": "What is the difference between Iterator and ListIterator?", "type": "mc", "opts": ["ListIterator is bidirectional", "No difference", "Iterator is faster", "ListIterator only for Sets"], "ans": 0},
            {"q": "Which collection is best for frequent insertions/deletions in the middle?", "type": "mc", "opts": ["ArrayList", "LinkedList", "HashSet", "TreeSet"], "ans": 1},
            {"q": "What is a ConcurrentHashMap?", "type": "mc", "opts": ["Thread-safe HashMap", "Concurrent operations map", "Copy of HashMap", "Sorted HashMap"], "ans": 0},
            {"q": "Can you modify a collection while iterating with for-each loop?", "type": "tf", "ans": False},
        ],
        "Exception Handling": [
            {"q": "What is an exception in Java?", "type": "mc", "opts": ["An abnormal condition", "A syntax error", "A warning", "A compiler message"], "ans": 0},
            {"q": "Which keyword is used to throw an exception manually?", "type": "fb", "ans": ["throw"]},
            {"q": "What is the parent class of all exceptions?", "type": "mc", "opts": ["Exception", "Throwable", "RuntimeException", "Error"], "ans": 1},
            {"q": "Can you have multiple catch blocks for a single try?", "type": "tf", "ans": True},
            {"q": "What is the difference between checked and unchecked exceptions?", "type": "mc", "opts": ["Checked must be handled, unchecked can be ignored", "No difference", "Checked are faster", "Unchecked must be declared"], "ans": 0},
            {"q": "Which exception is thrown when dividing by zero?", "type": "mc", "opts": ["NullPointerException", "ArithmeticException", "NumberFormatException", "DivideByZeroException"], "ans": 1},
            {"q": "What is the purpose of the 'finally' block?", "type": "mc", "opts": ["Executes regardless of exception", "Handles exceptions", "Throws exceptions", "Catches errors"], "ans": 0},
            {"q": "Can a finally block be skipped?", "type": "tf", "ans": False},
            {"q": "What keyword is used to declare exceptions in method signature?", "type": "fb", "ans": ["throws"]},
            {"q": "Is NullPointerException checked or unchecked?", "type": "mc", "opts": ["Checked", "Unchecked", "Both", "Neither"], "ans": 1},
            {"q": "Can you re-throw an exception?", "type": "tf", "ans": True},
            {"q": "What is try-with-resources?", "type": "mc", "opts": ["Automatic resource management", "Resource allocation", "Exception handling", "Memory management"], "ans": 0},
            {"q": "Can you have a try block without catch?", "type": "tf", "ans": True},
            {"q": "What is a custom exception?", "type": "mc", "opts": ["User-defined exception class", "Built-in exception", "System exception", "Runtime exception"], "ans": 0},
            {"q": "Which exception is thrown for array index out of bounds?", "type": "fb", "ans": ["ArrayIndexOutOfBoundsException", "ArrayIndexOutOfBounds"]},
            {"q": "Can finally block contain return statement?", "type": "tf", "ans": True},
        ],
        "Streams and Lambda Expressions": [
            {"q": "What is a lambda expression in Java?", "type": "mc", "opts": ["Anonymous function", "Named function", "Class method", "Static method"], "ans": 0},
            {"q": "Which Java version introduced lambda expressions?", "type": "fb", "ans": ["Java 8", "8"]},
            {"q": "What is a functional interface?", "type": "mc", "opts": ["Interface with single abstract method", "Interface with multiple methods", "Functional class", "Abstract class"], "ans": 0},
            {"q": "Can a lambda expression have multiple parameters?", "type": "tf", "ans": True},
            {"q": "What is the Stream API used for?", "type": "mc", "opts": ["Processing collections functionally", "I/O operations", "Thread management", "Network streaming"], "ans": 0},
            {"q": "What does the 'filter' operation do in Stream?", "type": "mc", "opts": ["Selects elements matching criteria", "Transforms elements", "Sorts elements", "Counts elements"], "ans": 0},
            {"q": "What does the 'map' operation do?", "type": "mc", "opts": ["Transforms each element", "Filters elements", "Creates Map collection", "Maps keys to values"], "ans": 0},
            {"q": "Is Stream processing lazy or eager?", "type": "mc", "opts": ["Lazy", "Eager", "Both", "Neither"], "ans": 0},
            {"q": "Can you reuse a Stream after terminal operation?", "type": "tf", "ans": False},
            {"q": "What is a method reference?", "type": "mc", "opts": ["Shorthand for lambda", "Reference to method", "Method pointer", "Static reference"], "ans": 0},
            {"q": "What operator is used for method reference?", "type": "fb", "ans": ["::", "double colon"]},
            {"q": "What is the difference between 'map' and 'flatMap'?", "type": "mc", "opts": ["flatMap flattens nested streams", "No difference", "map is faster", "flatMap only for arrays"], "ans": 0},
            {"q": "What does 'collect' operation do?", "type": "mc", "opts": ["Converts stream to collection", "Collects garbage", "Counts elements", "Sorts stream"], "ans": 0},
            {"q": "Can Streams be parallel?", "type": "tf", "ans": True},
            {"q": "What is the purpose of 'reduce' operation?", "type": "mc", "opts": ["Combine elements to single result", "Reduce size", "Filter elements", "Sort elements"], "ans": 0},
            {"q": "What annotation marks a functional interface?", "type": "fb", "ans": ["@FunctionalInterface", "FunctionalInterface"]},
        ],
        "Concurrency and Multithreading": [
            {"q": "What is a thread in Java?", "type": "mc", "opts": ["Lightweight process", "Heavy process", "Function", "Class"], "ans": 0},
            {"q": "Which class is used to create a thread?", "type": "mc", "opts": ["Thread", "Runnable", "Both Thread and Runnable", "Executor"], "ans": 2},
            {"q": "What method starts a thread execution?", "type": "fb", "ans": ["start()", "start"]},
            {"q": "Can you call run() method directly instead of start()?", "type": "tf", "ans": True},
            {"q": "What is synchronization in Java?", "type": "mc", "opts": ["Controlling thread access to shared resources", "Running threads simultaneously", "Thread creation", "Thread termination"], "ans": 0},
            {"q": "Which keyword is used for synchronization?", "type": "fb", "ans": ["synchronized"]},
            {"q": "What is a deadlock?", "type": "mc", "opts": ["Two threads waiting for each other", "Thread termination", "Thread creation failure", "Memory leak"], "ans": 0},
            {"q": "What is the ExecutorService used for?", "type": "mc", "opts": ["Managing thread pool", "Executing methods", "Service management", "Thread creation"], "ans": 0},
            {"q": "Can multiple threads execute synchronized method simultaneously?", "type": "tf", "ans": False},
            {"q": "What is a volatile variable?", "type": "mc", "opts": ["Variable visible to all threads", "Variable that changes", "Temporary variable", "Static variable"], "ans": 0},
            {"q": "What is the difference between wait() and sleep()?", "type": "mc", "opts": ["wait() releases lock, sleep() doesn't", "No difference", "sleep() is faster", "wait() is deprecated"], "ans": 0},
            {"q": "What package contains concurrent utilities?", "type": "fb", "ans": ["java.util.concurrent", "concurrent"]},
            {"q": "What is a CountDownLatch?", "type": "mc", "opts": ["Synchronization aid for thread coordination", "Counting utility", "Latch mechanism", "Thread counter"], "ans": 0},
            {"q": "Can you create a thread by implementing Runnable interface?", "type": "tf", "ans": True},
            {"q": "What is a thread pool?", "type": "mc", "opts": ["Collection of pre-created threads", "Thread storage", "Thread queue", "Memory pool"], "ans": 0},
            {"q": "What is the Fork/Join framework used for?", "type": "mc", "opts": ["Parallel task execution", "Forking processes", "Joining threads", "Creating branches"], "ans": 0},
        ],
    },
    "cpp": {
        "Pointers and Memory Management": [
            {"q": "What is a pointer in C++?", "type": "mc", "opts": ["Variable that stores memory address", "Variable that points to functions", "Type of array", "Reference variable"], "ans": 0},
            {"q": "What operator is used to get the address of a variable?", "type": "fb", "ans": ["&", "ampersand"]},
            {"q": "What is the difference between 'new' and 'malloc'?", "type": "mc", "opts": ["new calls constructor, malloc doesn't", "No difference", "malloc is faster", "new is deprecated"], "ans": 0},
            {"q": "Can you have a null pointer in C++?", "type": "tf", "ans": True},
            {"q": "What is a dangling pointer?", "type": "mc", "opts": ["Pointer to deallocated memory", "Hanging pointer", "Null pointer", "Wild pointer"], "ans": 0},
            {"q": "What keyword is used to deallocate memory?", "type": "fb", "ans": ["delete"]},
            {"q": "What is pointer arithmetic?", "type": "mc", "opts": ["Operations on pointer addresses", "Mathematical operations", "Arithmetic on values", "Pointer calculations"], "ans": 0},
            {"q": "Can you perform arithmetic on void pointers directly?", "type": "tf", "ans": False},
            {"q": "What is a double pointer?", "type": "mc", "opts": ["Pointer to pointer", "Two pointers", "Double precision pointer", "Pointer with double value"], "ans": 0},
            {"q": "What is the size of a pointer on 64-bit system?", "type": "fb", "ans": ["8 bytes", "8"]},
            {"q": "What is a memory leak?", "type": "mc", "opts": ["Memory not deallocated", "Memory overflow", "Pointer error", "Stack overflow"], "ans": 0},
            {"q": "Can arrays decay to pointers?", "type": "tf", "ans": True},
            {"q": "What is the difference between delete and delete[]?", "type": "mc", "opts": ["delete[] for arrays, delete for single objects", "No difference", "delete[] is faster", "delete for arrays"], "ans": 0},
            {"q": "What is RAII principle?", "type": "mc", "opts": ["Resource Acquisition Is Initialization", "Random Access Initialization", "Reference Allocation Interface", "Resource Automatic Instantiation"], "ans": 0},
            {"q": "Can you have a pointer to a function?", "type": "tf", "ans": True},
            {"q": "What does 'nullptr' represent?", "type": "mc", "opts": ["Type-safe null pointer", "Zero value", "Empty pointer", "Void pointer"], "ans": 0},
        ],
        "Classes and Object-Oriented Programming": [
            {"q": "What is a class in C++?", "type": "mc", "opts": ["User-defined data type", "Built-in type", "Function", "Variable"], "ans": 0},
            {"q": "What is the default access specifier for class members?", "type": "fb", "ans": ["private"]},
            {"q": "What is a constructor?", "type": "mc", "opts": ["Special function to initialize objects", "Destructor", "Member function", "Static function"], "ans": 0},
            {"q": "Can a class have multiple constructors?", "type": "tf", "ans": True},
            {"q": "What is a destructor?", "type": "mc", "opts": ["Function called when object is destroyed", "Constructor", "Member function", "Static function"], "ans": 0},
            {"q": "What symbol precedes a destructor name?", "type": "fb", "ans": ["~", "tilde"]},
            {"q": "Can you have virtual destructor?", "type": "tf", "ans": True},
            {"q": "What is the 'this' pointer?", "type": "mc", "opts": ["Pointer to current object", "Pointer to class", "Static pointer", "Function pointer"], "ans": 0},
            {"q": "What is operator overloading?", "type": "mc", "opts": ["Defining custom behavior for operators", "Loading operators", "Overriding operators", "Operator functions"], "ans": 0},
            {"q": "Can you overload the '::' operator?", "type": "tf", "ans": False},
            {"q": "What is a copy constructor?", "type": "mc", "opts": ["Constructor that creates copy of object", "Constructor for copying", "Duplicate constructor", "Clone constructor"], "ans": 0},
            {"q": "What is the rule of three?", "type": "mc", "opts": ["Destructor, copy constructor, copy assignment", "Three constructors", "Three members", "Three classes"], "ans": 0},
            {"q": "Can static member functions access non-static members directly?", "type": "tf", "ans": False},
            {"q": "What is a friend function?", "type": "mc", "opts": ["Function that can access private members", "Member function", "Static function", "Virtual function"], "ans": 0},
            {"q": "What keyword is used to define a constant member function?", "type": "fb", "ans": ["const"]},
            {"q": "Can you have a pure virtual destructor?", "type": "tf", "ans": True},
        ],
        "Inheritance and Polymorphism": [
            {"q": "What is inheritance in C++?", "type": "mc", "opts": ["Deriving new class from existing class", "Creating objects", "Function reuse", "Variable sharing"], "ans": 0},
            {"q": "Does C++ support multiple inheritance?", "type": "tf", "ans": True},
            {"q": "What is the diamond problem?", "type": "mc", "opts": ["Ambiguity in multiple inheritance", "Diamond-shaped class", "Memory problem", "Pointer issue"], "ans": 0},
            {"q": "What is virtual inheritance?", "type": "mc", "opts": ["Solution to diamond problem", "Virtual functions", "Abstract inheritance", "Interface inheritance"], "ans": 0},
            {"q": "What is polymorphism?", "type": "mc", "opts": ["Many forms of a single entity", "Multiple classes", "Many functions", "Multiple threads"], "ans": 0},
            {"q": "What keyword is used for runtime polymorphism?", "type": "fb", "ans": ["virtual"]},
            {"q": "Can you override a non-virtual function?", "type": "tf", "ans": True},
            {"q": "What is a pure virtual function?", "type": "mc", "opts": ["Virtual function with no implementation", "Virtual function", "Pure function", "Abstract function"], "ans": 0},
            {"q": "What makes a class abstract?", "type": "mc", "opts": ["Having at least one pure virtual function", "Using abstract keyword", "Private constructor", "No members"], "ans": 0},
            {"q": "Can you instantiate an abstract class?", "type": "tf", "ans": False},
            {"q": "What is the override keyword used for?", "type": "mc", "opts": ["Explicitly mark overriding functions", "Override variables", "Override classes", "Override operators"], "ans": 0},
            {"q": "What is the final keyword in C++11?", "type": "mc", "opts": ["Prevent function override or class inheritance", "Final variable", "Last function", "Constant"], "ans": 0},
            {"q": "Can you call virtual function in constructor?", "type": "tf", "ans": True},
            {"q": "What is early binding?", "type": "mc", "opts": ["Compile-time binding", "Runtime binding", "Early function call", "Static binding"], "ans": 0},
            {"q": "What is late binding?", "type": "fb", "ans": ["Run-time", "Runtime", "dynamic"]},
            {"q": "Can you have virtual constructor?", "type": "tf", "ans": False},
        ],
        "Templates and Generic Programming": [
            {"q": "What is a template in C++?", "type": "mc", "opts": ["Blueprint for generic code", "Code template", "Function pattern", "Class pattern"], "ans": 0},
            {"q": "Can templates be used for both functions and classes?", "type": "tf", "ans": True},
            {"q": "What keyword is used to define a template?", "type": "fb", "ans": ["template"]},
            {"q": "What is template specialization?", "type": "mc", "opts": ["Custom implementation for specific type", "Special template", "Template variation", "Specialized function"], "ans": 0},
            {"q": "Can you have non-type template parameters?", "type": "tf", "ans": True},
            {"q": "What is the difference between class and typename in templates?", "type": "mc", "opts": ["No functional difference", "class is older", "typename is better", "class for classes only"], "ans": 0},
            {"q": "What is SFINAE?", "type": "mc", "opts": ["Substitution Failure Is Not An Error", "Safe Function Interface", "Static Function Analysis", "Specialized Function Application"], "ans": 0},
            {"q": "Can templates be recursive?", "type": "tf", "ans": True},
            {"q": "What is variadic template?", "type": "mc", "opts": ["Template with variable number of parameters", "Variable template", "Array template", "Dynamic template"], "ans": 0},
            {"q": "What operator is used in variadic templates?", "type": "fb", "ans": ["...", "ellipsis"]},
            {"q": "Can you specialize template for pointer types?", "type": "tf", "ans": True},
            {"q": "What is template metaprogramming?", "type": "mc", "opts": ["Compile-time computation using templates", "Runtime templates", "Meta classes", "Template optimization"], "ans": 0},
            {"q": "Can template parameters have default values?", "type": "tf", "ans": True},
            {"q": "What is the syntax for function template?", "type": "mc", "opts": ["template<typename T> function", "template function", "generic function", "function<T>"], "ans": 0},
            {"q": "What is explicit template instantiation?", "type": "mc", "opts": ["Manually instantiating template", "Explicit keyword", "Instant template", "Fast template"], "ans": 0},
            {"q": "Can you have template template parameters?", "type": "tf", "ans": True},
        ],
        "STL Containers and Algorithms": [
            {"q": "What does STL stand for?", "type": "fb", "ans": ["Standard Template Library", "STL"]},
            {"q": "Which header contains vector?", "type": "mc", "opts": ["<vector>", "<array>", "<list>", "<container>"], "ans": 0},
            {"q": "Is vector a contiguous memory container?", "type": "tf", "ans": True},
            {"q": "What is the time complexity of vector push_back?", "type": "mc", "opts": ["Amortized O(1)", "O(n)", "O(log n)", "O(n²)"], "ans": 0},
            {"q": "What is the difference between vector and list?", "type": "mc", "opts": ["vector is contiguous, list is linked", "No difference", "list is faster", "vector is linked"], "ans": 0},
            {"q": "Can map have duplicate keys?", "type": "tf", "ans": False},
            {"q": "What container allows duplicate keys?", "type": "fb", "ans": ["multimap"]},
            {"q": "What is the underlying structure of map?", "type": "mc", "opts": ["Red-Black tree", "Hash table", "Array", "Linked list"], "ans": 0},
            {"q": "What is unordered_map based on?", "type": "mc", "opts": ["Hash table", "Tree", "Array", "List"], "ans": 0},
            {"q": "Can you use custom comparator with set?", "type": "tf", "ans": True},
            {"q": "What is the difference between set and unordered_set?", "type": "mc", "opts": ["set is ordered, unordered_set is not", "No difference", "unordered_set is sorted", "set uses hash"], "ans": 0},
            {"q": "What algorithm is used for sorting in STL?", "type": "mc", "opts": ["Introsort", "Quicksort", "Mergesort", "Heapsort"], "ans": 0},
            {"q": "What header contains algorithms?", "type": "fb", "ans": ["<algorithm>", "algorithm"]},
            {"q": "Can iterators be invalidated?", "type": "tf", "ans": True},
            {"q": "What is std::find used for?", "type": "mc", "opts": ["Finding element in range", "Finding file", "Search algorithm", "Binary search"], "ans": 0},
            {"q": "What is the time complexity of map find?", "type": "fb", "ans": ["O(log n)", "logarithmic"]},
        ],
        "Smart Pointers and Modern C++": [
            {"q": "What is a smart pointer?", "type": "mc", "opts": ["Pointer with automatic memory management", "Intelligent pointer", "Fast pointer", "Special pointer"], "ans": 0},
            {"q": "Which header contains smart pointers?", "type": "fb", "ans": ["<memory>", "memory"]},
            {"q": "What is unique_ptr?", "type": "mc", "opts": ["Exclusive ownership smart pointer", "Unique pointer value", "Single pointer", "Special pointer"], "ans": 0},
            {"q": "Can you copy a unique_ptr?", "type": "tf", "ans": False},
            {"q": "What is shared_ptr?", "type": "mc", "opts": ["Shared ownership smart pointer", "Shared pointer value", "Multiple pointers", "Reference pointer"], "ans": 0},
            {"q": "What mechanism does shared_ptr use?", "type": "fb", "ans": ["Reference counting", "refcount"]},
            {"q": "Can shared_ptr have cyclic references?", "type": "tf", "ans": True},
            {"q": "What is weak_ptr used for?", "type": "mc", "opts": ["Breaking cyclic references", "Weak references", "Temporary pointers", "Weak ownership"], "ans": 0},
            {"q": "What function creates shared_ptr?", "type": "fb", "ans": ["std::make_shared", "make_shared"]},
            {"q": "Is make_shared more efficient than new?", "type": "tf", "ans": True},
            {"q": "What is std::move?", "type": "mc", "opts": ["Transfer ownership/resources", "Move memory", "Relocate pointer", "Shift data"], "ans": 0},
            {"q": "What is an rvalue reference?", "type": "mc", "opts": ["Reference to temporary object", "Right value", "Reference value", "Reverse reference"], "ans": 0},
            {"q": "What symbol denotes rvalue reference?", "type": "fb", "ans": ["&&", "double ampersand"]},
            {"q": "Can you have smart pointer to array?", "type": "tf", "ans": True},
            {"q": "What is perfect forwarding?", "type": "mc", "opts": ["Forwarding arguments preserving value category", "Perfect function call", "Forward declaration", "Template forwarding"], "ans": 0},
            {"q": "What is the rule of five?", "type": "mc", "opts": ["Destructor, copy/move constructors, copy/move assignments", "Five constructors", "Five rules", "Five members"], "ans": 0},
        ],
        "Move Semantics and Advanced Features": [
            {"q": "What is move semantics?", "type": "mc", "opts": ["Transferring resources without copying", "Moving objects", "Semantic analysis", "Object relocation"], "ans": 0},
            {"q": "What is the benefit of move semantics?", "type": "mc", "opts": ["Performance improvement", "Easier syntax", "Better readability", "Simpler code"], "ans": 0},
            {"q": "Can you move from const objects?", "type": "tf", "ans": False},
            {"q": "What is std::forward used for?", "type": "mc", "opts": ["Perfect forwarding", "Forward declaration", "Forwarding pointers", "Forward iteration"], "ans": 0},
            {"q": "What is a lambda expression?", "type": "mc", "opts": ["Anonymous function", "Lambda calculus", "Greek letter", "Function pointer"], "ans": 0},
            {"q": "What syntax starts a lambda?", "type": "fb", "ans": ["[]", "square brackets"]},
            {"q": "Can lambdas capture variables?", "type": "tf", "ans": True},
            {"q": "What does [=] capture in lambda?", "type": "mc", "opts": ["All by value", "All by reference", "Nothing", "Everything"], "ans": 0},
            {"q": "What does [&] capture in lambda?", "type": "mc", "opts": ["All by reference", "All by value", "Address", "Nothing"], "ans": 0},
            {"q": "What is constexpr?", "type": "mc", "opts": ["Compile-time constant expression", "Constant expression", "Expression constraint", "Constant string"], "ans": 0},
            {"q": "Can constexpr functions be evaluated at runtime?", "type": "tf", "ans": True},
            {"q": "What is decltype?", "type": "mc", "opts": ["Query type of expression", "Declare type", "Type declaration", "Define type"], "ans": 0},
            {"q": "What keyword allows automatic type deduction?", "type": "fb", "ans": ["auto"]},
            {"q": "Can you use auto for function return type?", "type": "tf", "ans": True},
            {"q": "What is structured binding?", "type": "mc", "opts": ["Decomposing objects into variables", "Structure definition", "Binding structures", "Struct initialization"], "ans": 0},
            {"q": "What C++ standard introduced structured bindings?", "type": "fb", "ans": ["C++17", "17"]},
        ],
    },
}

def generate_questions_for_topic(language, topic, templates):
    """Generate questions for a specific topic - one question per template (no duplication)"""
    questions = []
    base_templates = templates.get(topic, [])
    
    # Generate one question per unique template (no replication)
    for template in base_templates:
        q_data = {
            "questionText": template["q"],
            "maxScore": 1,
            "difficulty": random.choice(["easy", "medium", "hard"]),
            "category": "Programming",
            "topic": topic,
            "tags": [language, topic]
        }
        
        if template["type"] == "mc":
            q_data["questionType"] = "multiple-choice"
            q_data["options"] = template["opts"]
            q_data["correctAnswer"] = template["opts"][template["ans"]]
        elif template["type"] == "tf":
            q_data["questionType"] = "true-false"
            q_data["correctAnswer"] = "True" if template["ans"] else "False"
        elif template["type"] == "fb":
            q_data["questionType"] = "fill-in-the-blank"
            q_data["blankAnswers"] = template["ans"]
            q_data["caseSensitive"] = False
        
        questions.append(q_data)
    
    return questions

def generate_all_questions():
    """Generate complete question bank - one question per unique template"""
    question_bank = {}
    
    for language, topics in QUESTION_TEMPLATES.items():
        print(f"Generating questions for {language.upper()}...")
        all_questions = []
        
        for topic, templates in topics.items():
            topic_questions = generate_questions_for_topic(language, topic, {topic: templates})
            all_questions.extend(topic_questions)
            print(f"  ✓ {topic}: {len(topic_questions)} unique questions")
        
        question_bank[language] = all_questions
        print(f"  Total: {len(all_questions)} unique questions\n")
    
    return question_bank

def main():
    print("="*70)
    print("Comprehensive Question Bank Generator")
    print("="*70 + "\n")
    
    # Generate questions
    question_bank = generate_all_questions()
    
    # Statistics
    total = sum(len(q) for q in question_bank.values())
    print(f"\n{'='*70}")
    print("Generation Complete!")
    print(f"{'='*70}")
    print(f"Total Languages: {len(question_bank)}")
    print(f"Total Questions: {total}")
    
    # Save
    output_file = "../backend/src/data/questionBankGenerated.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(question_bank, f, indent=2, ensure_ascii=False)
    
    print(f"\n✓ Saved to: {output_file}")
    print("="*70 + "\n")

if __name__ == "__main__":
    main()
